### ISSUE TITLE
Right-clicking while planning a flight creates new waypoint

### ISSUE THREAD

**Issue by Konaber** [ServError/IL2-Mission-Planner#11]
Right-clicking while planning a flight is creating a new waypoint (same behaviour as left clicking).
This means if you plan a long flight, you can't move beyond the current boundaries (without zooming out)
of the current screen.

Would be nice to only add new waypoints with left click and to be able to move through the map while holding the right mouse down.

**Comment by ServError** [comment]
I'm pushing a fix for this now. It was a bug that crept in transitioning between leaflet/draw versions and caused this behavior as well as poor phone browser behavior. It wont be split as left/right click, but rather just that dragging with the left no longer makes new waypoints unintentionally.
